import { StyleSheet } from "react-native";

const getStyle = ({ width, height }: { width: number; height: number }) => StyleSheet.create({
    container: {
        ...StyleSheet.absoluteFillObject,
        height: height,
        width: width,
    },
    map: {
        height: height - 80,
        width: width,
    },
    container1: {
        alignItems: 'center',
        //backgroundColor:"red"
    },
    image: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 3,
        borderColor: '#fff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
        //backgroundColor:"green"
    },
    imageView: {
        width: 300,
        height: 300,
        borderRadius: 20,
        borderWidth: 3,
        borderColor: '#fff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
        backgroundColor: "white",
        marginBottom: 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    pointer: {
        width: 0,
        height: 0,
        borderLeftWidth: 6,
        borderRightWidth: 6,
        borderTopWidth: 10,
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        borderTopColor: '#fff',
        marginTop: -2,
    },
    modal: {
        //backgroundColor:"green"
    },
    loadingContainer: {
        position: 'absolute',
        top: 50,
        left: 0,
        right: 0,
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        padding: 20,
        margin: 20,
        borderRadius: 10,
    },
    photosLoadingContainer: {
        position: 'absolute',
        top: 100,
        left: 0,
        right: 0,
        alignItems: 'center',
        backgroundColor: 'rgba(0, 150, 255, 0.9)',
        padding: 15,
        margin: 20,
        borderRadius: 10,
    },
    loadingText: {
        fontSize: 16,
        fontWeight: '500',
        color: '#fff',
    },
    errorContainer: {
        position: 'absolute',
        top: 50,
        left: 0,
        right: 0,
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        padding: 20,
        margin: 20,
        borderRadius: 10,
    },
    errorText: {
        fontSize: 16,
        fontWeight: '500',
        marginBottom: 10,
        color: 'red',
    },
    infoContainer: {
        position: 'absolute',
        top: 50,
        right: 20,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        padding: 10,
        borderRadius: 10,
        flexDirection: 'row',
        alignItems: 'center',
    },
    infoText: {
        color: '#fff',
        fontSize: 14,
        marginRight: 10,
    },
    refreshButton: {
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
        borderRadius: 15,
        width: 30,
        height: 30,
        justifyContent: 'center',
        alignItems: 'center',
    },
    refreshText: {
        fontSize: 16,
    },
    showAllButton: {
        position: 'absolute',
        bottom: 100,
        right: 20,
        backgroundColor: '#007AFF',
        paddingHorizontal: 15,
        paddingVertical: 10,
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
    showAllText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },

})

export default getStyle;